root = "."
cmd = "air"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "magenta"
